version: '2'
services:
  grafana_graphite:
    build: docker-grafana-graphite/.
    container_name: grafana-dashboard
    ports:
      - '80:80'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
      - '2004:2004'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - ./log/supervisor:/var/log/supervisor
  management_center:
    container_name: management-center
    image: hazelcast/management-center:latest
    ports:
      - '8080:8080'
    environment:
      - MC_DEFAULT_CLUSTER=FlightTelemetry
      - MC_DEFAULT_CLUSTER_MEMBERS=${FLIGHT_TELEMETRY_HZ_MEMBER_LIST}
