# Set ADSB exchange API key for telemetry demo
export FLIGHT_TELEMETRY_ADSB_EXCHANGE_API_KEY=
export FLIGHT_TELEMETRY_ADSB_EXCHANGE_API_HOST=adsbexchange-com1.p.rapidapi.com
export FLIGHT_TELEMETRY_SINK_HOST=127.0.0.1
export FLIGHT_TELEMETRY_WRITE_TO_FILE=false
export FLIGHT_TELEMETRY_USE_OFFLINE_DATA=true
export FLIGHT_TELEMETRY_HZ_MEMBER_LIST=127.0.0.1
